# Generated by Django 6.0.3 on 2026-04-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('auth_provider', models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('supabase', 'Supabase')], default='local', max_length=20)),
                ('external_auth_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('app_type', models.CharField(choices=[('analysis', 'Analysis')], default='analysis', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('spec_generated', 'Spec Generated'), ('scaffolding', 'Scaffolding'), ('generated', 'Generated'), ('preview_starting', 'Preview Starting'), ('preview_running', 'Preview Running'), ('preview_failed', 'Preview Failed'), ('deploy_pending', 'Deploy Pending'), ('deployed', 'Deployed'), ('failed', 'Failed')], default='draft', max_length=40)),
                ('original_prompt', models.TextField()),
                ('spec_json', models.JSONField(blank=True, default=dict)),
                ('project_root', models.CharField(blank=True, max_length=500)),
                ('entry_file', models.CharField(blank=True, max_length=255)),
                ('preview_port', models.PositiveIntegerField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True)),
                ('preview_pid', models.IntegerField(blank=True, null=True)),
                ('production_url', models.URLField(blank=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_apps', to='core.appuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromptEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('assistant', 'Assistant')], default='user', max_length=20)),
                ('event_type', models.CharField(choices=[('initial_prompt', 'Initial Prompt'), ('refine_prompt', 'Refine Prompt'), ('status_change', 'Status Change'), ('error', 'Error'), ('system_message', 'System Message')], default='initial_prompt', max_length=30)),
                ('content', models.TextField()),
                ('generated_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_events', to='core.generatedapp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_events', to='core.appuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromptSesstion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_prompt', models.TextField()),
                ('prompt_type', models.CharField(choices=[('analysis', 'Analysis')], default='analysis', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('spec_generating', 'Spec Generating'), ('spec_generated', 'Spec Generated'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_sessions', to='core.appuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='generatedapp',
            name='prompt_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_specs', to='core.promptsesstion'),
        ),
    ]
