# Generated by Django 6.0.3 on 2026-04-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_promptsesstion_promptsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='auth_provider',
        ),
        migrations.AddField(
            model_name='appuser',
            name='auth_system',
            field=models.CharField(choices=[('local', 'Local'), ('supabase', 'Supabase')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='identity_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
