# Generated by Django 6.0.3 on 2026-04-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_appuser_auth_provider_appuser_auth_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedapp',
            name='original_prompt',
        ),
    ]
