# Generated by Django 6.0.3 on 2026-04-08 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_generatedapp_original_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedapp',
            name='prompt_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_apps', to='core.promptsession'),
        ),
        migrations.AlterField(
            model_name='promptsession',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', max_length=20),
        ),
    ]
